name: Pull request

on:
  pull_request:
    branches:
      - main

env:
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE__SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE__TENANT_ID }}
    ARM_CLIENT_ID: ${{ secrets.AZURE__CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZURE__CLIENT_SECRET }}
    TF_LOG: "INFO"

jobs:
  dev:
    name: Plan dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.2

      - name: Terraform init
        run: terraform init

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false -var-file="$GITHUB_WORKSPACE/environments/dev.tfvars" # -out main.tfplan

      # - name: Terraform apply
      #   run: terraform apply -auto-approve main.tfplan

# Check has latest changes from main
# Merge PR to merge branch