name: Pull request

on:
  pull_request:
    branches:
      - main

env:
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE__SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE__TENANT_ID }}
    ARM_CLIENT_ID: ${{ secrets.AZURE__CLIENT_ID }}
    ARM_CLIENT_SECRET: ${{ secrets.AZURE__CLIENT_SECRET }}
    TF_LOG: "INFO"

jobs:
  dev:
    name: Deploy to development
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        uses: ./.github/actions/deploy-terraform
        with:
          workspace: "dev"

  prod:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: prod
    needs: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy
        uses: ./.github/actions/deploy-terraform
        with:
          workspace: "prod"