name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  dev:
    name: Deploy to dev
    uses: ./.github/workflows/deploy-terraform.yaml
    with:
      gith-environment: dev
      terraform-workspace: dev
    secrets: inherit
  
  prod:
    name: Deploy to prod
    uses: ./.github/workflows/deploy-terraform.yaml
    with:
      gith-environment: prod
      terraform-workspace: prod
    needs: dev
    secrets: inherit