name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  preview-plan-dev:
    name: Preview dev plan
    uses: ./.github/workflows/deploy-terraform.yaml
    with:
      gith-environment: dev
      terraform-workspace: dev
      apply: false
    secrets: inherit

  deploy-dev:
    name: Deploy dev plan
    uses: ./.github/workflows/deploy-terraform.yaml
    with:
      gith-environment: dev
      terraform-workspace: dev
      apply: true
    needs: preview-plan-dev
    secrets: inherit
  
  preview-prod-plan:
    name: Preview prod plan
    uses: ./.github/workflows/deploy-terraform.yaml
    with:
      gith-environment: prod
      terraform-workspace: prod
      apply: false
    needs: deploy-dev
    secrets: inherit

  deploy-prod:
    name: Deploy prod plan
    uses: ./.github/workflows/deploy-terraform.yaml
    with:
      gith-environment: prod
      terraform-workspace: prod
      apply: true
    needs: preview-prod-plan
    secrets: inherit