name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  validate-terraform:
    if: github.actor != 'dependabot[bot]'
    name: Validate Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Initialize Terraform
        run: terraform init -backend=false
        shell: bash

      - name: Select Terraform workspace
        run: terraform workspace select -or-create=true dev
        shell: bash

      - name: Check Terraform format
        run: terraform fmt -check -list=true
        shell: bash

      - name: Validate code
        run: terraform validate
        shell: bash

  preview-plan-dev:
    name: Preview dev plan
    uses: ./.github/workflows/deploy-terraform.yaml
    with:
      gith-environment: dev
      terraform-workspace: dev
      apply: false
    needs: validate-terraform
    secrets: inherit

  deploy-dev:
    name: Deploy dev plan
    uses: ./.github/workflows/deploy-terraform.yaml
    with:
      gith-environment: dev
      terraform-workspace: dev
      apply: true
    needs: preview-plan-dev
    secrets: inherit

  # preview-production-plan:
  #   name: Preview production plan
  #   uses: ./.github/workflows/deploy-terraform.yaml
  #   with:
  #     gith-environment: pro
  #     terraform-workspace: pro
  #     apply: false
  #   needs: deploy-dev
  #   secrets: inherit

  # deploy-production:
  #   name: Deploy pro plan
  #   uses: ./.github/workflows/deploy-terraform.yaml
  #   with:
  #     gith-environment: pro
  #     terraform-workspace: pro
  #     apply: true
  #   needs: preview-pro-plan
  #   secrets: inherit
